    const companys=[
  {
    "name": "VGP NV",
    "employee_count": 230,
    "mission_statement": "VGP VN is a real estate company. The company through its subsidiaries designs, constructs, and leases out logistics complexes and semi-industrial parks. Its business line includes Investment business, Property Development, and Property and asset management. The company derives the maximum rental income from the investment business. Geographically, it has a presence in Germany, Spain, Austria, Czech Republic, Slovakia, Hungary, Latvia, and Romania.",
    "logo_url": "",
    "images": [],
    "industry": "Real Estate",
    "id": 1,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "CTEK AB",
    "employee_count": null,
    "mission_statement": "CTEK AB engages in the manufacture and sale of battery chargers for vehicles. It also suppliers electric vehicle service equipment. The company was founded in 1997 and is headquartered in Vikmanshyttan, Sweden.",
    "logo_url": "",
    "images": ["https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/aa45540e-ad2a-40b5-a132-ff89d7cdfc33/air-zoom-alphafly-next-flyknit-road-racing-shoes-13jzhr.png"],
    "industry": "Electrical Equipment",
    "id": 2,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Azelis Group NV",
    "employee_count": null,
    "mission_statement": "Azelis Group NV functions as an investment holding company. It operates as a global innovation service provider for the specialty chemicals and food ingredients industry. The company was founded in 2001 and is headquartered in Antwerp, Belgium.",
    "logo_url": "",
    "images": [],
    "industry": "Chemicals",
    "id": 3,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Anora Group Oyj",
    "employee_count": null,
    "mission_statement": "Anora Group Oyj produces, distributes, markets, and sells alcoholic beverages. It offers wines, spirits, beers, and other alcoholic beverages, as well as provides distilling and bottling services. The company was founded on September 1, 2021 and is headquartered in Helsinki, Finland.",
    "logo_url": "",
    "images": [],
    "industry": "Food Products",
    "id": 4,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Sylvamo Corp.",
    "employee_count": null,
    "mission_statement": "Sylvamo Corp., operates as a papers company. It produces uncoated freesheet for paper products such as cut size and offset paper. The company markets pulp, aseptic & liquid packaging board and coated unbleached kraft papers. Sylvamo was founded in 1898 and is headquartered in Memphis, TN.",
    "logo_url": "",
    "images": [],
    "industry": "Paper & Forestry",
    "id": 5,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Minerals 260 Ltd.",
    "employee_count": null,
    "mission_statement": "Minerals 260 Ltd., operates as a blank check company. It is a special purpose acquisition company which is incorporated for the purpose of spinning out the Moora project and the Koojan JV project from Liontown Resources Limited. The company is headquartered in West Perth, Australia.",
    "logo_url": "",
    "images": [],
    "industry": "Precious Metals",
    "id": 6,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Olaplex Holdings, Inc.",
    "employee_count": null,
    "mission_statement": "Olaplex Holdings, Inc., is a science-enabled, technology-driven beauty company, focused on delivering its patent-protected hair care products to professional hair salons, retailers, and everyday consumers. The brand OLAPLEX is a patent-protected, proven, and potent haircare technology system that restores all hair types to its healthiest state possible. OLAPLEX created the Bond Building category which protects, strengthens, and rebuilds broken bonds in the hair during and after hair services. The company was founded in 2014 and is headquartered in Santa Barbara, CA.",
    "logo_url": "",
    "images": [],
    "industry": "Household Products",
    "id": 7,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "CapitaLand Investment Ltd.",
    "employee_count": null,
    "mission_statement": "CapitaLand Investment Ltd., is a real estate investment manager. It holds real estate assets and funds under its management. It carries out its operations in the Fee Income-related Business and Real Estate Investments segments. The Fee Income-related Business segment involves fund management and lodging management. The Real Estate Investments segment deals with stakes in both listed and unlisted funds, and investment properties. The company was founded on August 29, 2003 and is headquartered in Singapore.",
    "logo_url": "",
    "images": [],
    "industry": "Real Estate",
    "id": 8,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Castellum Helsinki Finance Holding Abp",
    "employee_count": null,
    "mission_statement": "Castellum Helsinki Finance Holding Abp is a Finnish private company located in Helsinki. The firm provides financial services.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 9,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Swiss Life Finance I Ltd.",
    "employee_count": null,
    "mission_statement": "Swiss Life Finance I Ltd., is a private company headquartered in Liechtenstein that provides financial services.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 10,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Universal Music Group BV",
    "employee_count": null,
    "mission_statement": "Universal Music Group NV engages in the music entertainment business. Its three main operating businesses are: recorded music; music publishing; and merchandising. The recorded music business discovers and develops artists, supports the creation of audio and audiovisual content by artists, and markets, distributes, sells and licenses such content to consumers across a wide array of formats and platforms. The music publishing business discovers and develops composers and songwriters and owns and administers the copyright to the musical and lyrical compositions created by such composers and songwriters, which is licensed for use in recordings, public performances and for related uses, such as in films and advertisements. The merchandising business produces and sells artist-branded products as well as other branded products. The firm's s recorded music business has offices in more than 60 territories and is present across approximately 200 markets, where markets may be defined by a number of factors, including language and dialects. Its major music markets including the United States, the United Kingdom, France and Germany. Universal Music Group was founded in 1924 and is headquartered in Hilversum, The Netherlands.",
    "logo_url": "",
    "images": [],
    "industry": "Media",
    "id": 11,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Northam Platinum Holdings Ltd.",
    "employee_count": null,
    "mission_statement": "Northam Platinum Holdings Ltd., mines for platinum and other minerals. Its primary products are the three main platinum group metals including: platinum, palladium and rhodium. The firm operates through Zondereinde Mine and Booysendal Mine. The company is headquartered in Waterfall City, South Africa.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Metals",
    "id": 12,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "European Wax Center, Inc.",
    "employee_count": 158,
    "mission_statement": "European Wax Center, Inc., engages in the provision of out-of-home hair removal services. Its menu of services is focused on body and facial waxing. It operates company-owned waxing centers and franchises its model. It also offers body, skincare, and brow products. The company was founded in 2004 and is headquartered in Plano, TX.",
    "logo_url": "",
    "images": [],
    "industry": "Consumer Services",
    "id": 13,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "India Cleantech Energy Ltd.",
    "employee_count": null,
    "mission_statement": "India Cleantech Energy Ltd., is a private company headquartered in Mauritius. The firm engages in clean energy solutions.",
    "logo_url": "",
    "images": [],
    "industry": "Utilities",
    "id": 14,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Stagwell, Inc.",
    "employee_count": null,
    "mission_statement": "Stagwell, Inc., operates as media and public relations agency. It delivers brands that connecting culture-moving creativity with technology to harmonize the art and science of marketing. The company is headquartered in New York, NY.",
    "logo_url": "",
    "images": [],
    "industry": "Commercial Services",
    "id": 15,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "SUEK Securities DAC",
    "employee_count": null,
    "mission_statement": "Suek Securities DAC is an Irish private company located in Dublin that engages in issuing notes.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 16,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Weber, Inc.",
    "employee_count": 2156,
    "mission_statement": "Weber, Inc., manufactures outdoor cooking equipment. Its products include traditional charcoal grills, gas grills, smokers, pellet and electric grills. The company was founded by George Stephen, Sr. in 1952 and is headquartered in Palatine, IL.",
    "logo_url": "",
    "images": [],
    "industry": "Consumer Durables",
    "id": 17,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "MC Brazil Downstream Trading SARL",
    "employee_count": null,
    "mission_statement": "MC Brazil Downstream Trading SARL, part of MC Brazil Downstream Participaçoes SA, is a company headquartered in Luxembourg, Luxembourg, that owns and operates petroleum refineries.",
    "logo_url": "",
    "images": [],
    "industry": "Refiners & Pipelines",
    "id": 18,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "FWD Group Ltd.",
    "employee_count": null,
    "mission_statement": "FWD ProInsure Ltd., is an investment holding company, which engages in the provision of life insurance, and general insurance. The company was founded on January 3, 2013 and is headquartered in Hong Kong.",
    "logo_url": "",
    "images": [],
    "industry": "Commercial Services",
    "id": 19,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-04T22:33:23.407210"
  },
  {
    "name": "Traeger, Inc.",
    "employee_count": 710,
    "mission_statement": "Traeger, Inc., designs, sells, and support wood pellet fueled barbeque grills. It specializes in wood pellet grill, an outdoor cooking system that ignites all-natural hardwoods to grill, smoke, bake, roast, braise, and barbeque. The company was founded on August 4, 2017 and is headquartered in Salt Lake City, UT.",
    "logo_url": "",
    "images": [],
    "industry": "Consumer Durables",
    "id": 20,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "SEGRO Capital SARL",
    "employee_count": null,
    "mission_statement": "SEGRO Capital SARL is a Luxembourgish private company located in Luxembourg. The firm provides investment services.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 21,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Alight, Inc.",
    "employee_count": null,
    "mission_statement": "Alight, Inc., provides cloud-based integrated digital human capital and business solutions. The company is headquartered in Lincolnshire, IL.",
    "logo_url": "",
    "images": [],
    "industry": "Software & Services",
    "id": 22,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Rallybio Corp.",
    "employee_count": null,
    "mission_statement": "Rallybio Corp., engages in the identification, research and development, and manufacture of clinical biotechnology products and therapies for severe and rare diseases. Its product candidates focuses in the areas of fetal and neonatal disorders, hematology, immuno-inflammation, and metabolic disease. The company was founded by Martin W. Mackay, Stephen Uden, and Jeffrey M. Fryer in January 2018 and is headquartered in New Haven, CT.",
    "logo_url": "",
    "images": [],
    "industry": "Commercial Services",
    "id": 23,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Payoneer Global, Inc.",
    "employee_count": null,
    "mission_statement": "Payoneer Global, Inc., is a global payment and commerce-enabling platform, which provides global payments and other services through APIs (Application Programming Interface) as well as web, mobile applications and machine learning infrastructure. The company was founded in 2005 and is headquartered in New York, NY.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 24,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Zevia PBC",
    "employee_count": null,
    "mission_statement": "Zevia PBC engages in the production of zero-calorie diet sodas. Its products include soda, sparkling water, energy drinks, mixers, kidz drinks and organic tea. The company was founded in 2007 and is headquartered in Los Angeles, CA.",
    "logo_url": "",
    "images": [],
    "industry": "Food Products",
    "id": 25,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Victoria's Secret & Co.",
    "employee_count": null,
    "mission_statement": "Victoria's Secret & Co., operates as a lingerie, clothing and beauty retailer. It offers bras, panties, lingerie, pajamas, sleep, sport and swim apparel, and beauty products. The company was founded in 1963 and is headquartered in Reynoldsburg, OH.",
    "logo_url": "",
    "images": [],
    "industry": "Retailing",
    "id": 26,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Electricidad Firme de Mexico Holdings SA de CV",
    "employee_count": null,
    "mission_statement": "Electricidad Firme de Mexico Holdings SA de CV, part of Saavi Energía S. de R.L. de C.V., is a Mexican company located in Miguel Hidalgo. The firm provides electricity services.",
    "logo_url": "",
    "images": [],
    "industry": "Utilities",
    "id": 27,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  },
  {
    "name": "Wise Plc",
    "employee_count": null,
    "mission_statement": "Wise Plc provides global payment solutions. It offers cross-border payment services to banks and customers. The company was founded by Kristo Käärmann and Taavet Hinrikus on February 02, 2018 and is headquartered in London, the United Kingdom.",
    "logo_url": "",
    "images": [],
    "industry": "Diversified Financials",
    "id": 28,
    "price_range": "",
    "certificates": [],
    "created_at": "2022-01-06T21:48:42.220593"
  }
]
export function getCompanies() {
    return companys;
}
export function getCompaniesById(id) {
    return companys.find((company) => (company.id == id));
}