export const demoBrands = [
  {
    id: 0,
    name: "Oral-B",
    parent: "Proctor & Gamble",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Procter_%26_Gamble_logo.svg/1200px-Procter_%26_Gamble_logo.svg.png",
    values_match_score: -1,
    diversity_pct_rank: .12,
    water_pct_rank: .24,
    carbon_intensity_pct_rank: .32,
    small_business_pct_rank: .46,
    waste_pct_rank: .53,
    human_rights_pct_rank: .23,
    business_ethics_pct_rank: .15,
  },
  {
    id: 1,
    name: "Quaker Oats",
    parent: "PepsiCo, Inc.",
    logo: "https://1000logos.net/wp-content/uploads/2020/08/PepsiCo-Logo-500x313.jpg",
    values_match_score: 0,
    diversity_pct_rank: .67,
    water_pct_rank: .32,
    carbon_intensity_pct_rank: .63,
    small_business_pct_rank: .74,
    waste_pct_rank: .15,
    human_rights_pct_rank: .26,
    business_ethics_pct_rank: .41,
  },
  {
    id: 2,
    name: "Converse",
    parent: "Nike, Inc.",
    logo: "https://i.ebayimg.com/images/g/mCMAAOSwQ-JalJ-V/s-l300.jpg",
    values_match_score: -5,
    diversity_pct_rank: .12,
    water_pct_rank: .02,
    carbon_intensity_pct_rank: .13,
    small_business_pct_rank: .04,
    waste_pct_rank: .09,
    human_rights_pct_rank: .26,
    business_ethics_pct_rank: .41,
  },
];
