export const demoBrands = [
  {
    id: 0,
    name: "Oral-B",
    parent: "Proctor & Gamble",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Procter_%26_Gamble_logo.svg/1200px-Procter_%26_Gamble_logo.svg.png",
    values_match_score: -1,
    diversity_pct_rank: "4",
    water_pct_rank: "4",
    carbon_intensity_pct_rank: "4",
    small_business_pct_rank: "4",
    waste_1: "4",
    human_rights_1: "4",
    business_ethics_1: "4",
  },
  {
    id: 1,
    name: "Quaker Oats",
    parent: "PepsiCo, Inc.",
    logo: "https://1000logos.net/wp-content/uploads/2020/08/PepsiCo-Logo-500x313.jpg",
    values_match_score: -0,
    diversity_pct_rank: "4",
    water_pct_rank: "4",
    carbon_intensity_pct_rank: "4",
    small_business_pct_rank: "4",
    waste_1: "4",
    human_rights_1: "4",
    business_ethics_1: "4",
  },
  {
    id: 2,
    name: "Converse",
    parent: "Nike, Inc.",
    logo: "https://i.ebayimg.com/images/g/mCMAAOSwQ-JalJ-V/s-l300.jpg",
    values_match_score: -5,
    diversity_pct_rank: "4",
    water_pct_rank: "4",
    carbon_intensity_pct_rank: "4",
    small_business_pct_rank: "4",
    waste_1: "4",
    human_rights_1: "4",
    business_ethics_1: "4",
  },
];
